scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: Remove over 0.35 meters on the right
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_footprint
        min_x: -3.5
        max_x: 3.5
        min_y: -3.5
        max_y: -0.35
        min_z: -0.1
        max_z: 0.1

    filter2:
      name: Remove over 0.35 meters on the left
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_footprint
        min_x: -3.5
        max_x: 3.5
        min_y: 0.35
        max_y: 3.5
        min_z: -0.1
        max_z: 0.1

    filter3:
      name: Remove 90 to 270 degree
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: 1.57
        upper_angle: 4.71

    filter4:
      name: exist range 0.12 to 0.7 meter
      type: laser_filters/LaserScanRangeFilter
      params:
        lower_threshold: 0.12
        upper_threshold: 0.7

    filter5:
      name: exist intensity 500 to 4000
      type: laser_filters/LaserScanIntensityFilter
      params:
        lower_threshold: 500.0
        upper_threshold: 4000.0
        disp_histogram: 0.0

    filter6:
      name: interpolation
      type: laser_filters/InterpolationFilter
