/**:
  controller_server:
    ros__parameters:
      # controller server parameters (see Controller Server for more info)
      use_sim_time: True
      controller_frequency: 20.0
      min_x_velocity_threshold: 0.001
      min_y_velocity_threshold: 0.5
      min_theta_velocity_threshold: 0.001
      progress_checker_plugins: ["progress_checker"] # progress_checker_plugin: "progress_checker" For Humble and older
      goal_checker_plugins: ["goal_checker"]
      controller_plugins: ["FollowPath"]
      progress_checker:
        plugin: "nav2_controller::SimpleProgressChecker"
        required_movement_radius: 0.5
        movement_time_allowance: 10.0
      goal_checker:
        plugin: "nav2_controller::SimpleGoalChecker"
        xy_goal_tolerance: 0.3
        yaw_goal_tolerance: 0.3
        stateful: True
      # DWB controller parameters
      FollowPath:
        plugin: "dwb_core::DWBLocalPlanner"
        debug_trajectory_details: True
        min_vel_x: 0.0
        min_vel_y: 0.0
        max_vel_x: 0.26
        max_vel_y: 0.0
        max_vel_theta: 1.0
        min_speed_xy: 0.0
        max_speed_xy: 0.26
        min_speed_theta: 0.0
        acc_lim_x: 2.5
        acc_lim_y: 0.0
        acc_lim_theta: 3.2
        decel_lim_x: -2.5
        decel_lim_y: 0.0
        decel_lim_theta: -3.2
        vx_samples: 20
        vy_samples: 5
        vtheta_samples: 20
        sim_time: 1.7
        linear_granularity: 0.05
        angular_granularity: 0.025
        transform_tolerance: 0.2
        xy_goal_tolerance: 0.25
        trans_stopped_velocity: 0.25
        short_circuit_trajectory_evaluation: True
        limit_vel_cmd_in_traj: False
        stateful: True
        critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
        BaseObstacle.scale: 0.02
        PathAlign.scale: 32.0
        GoalAlign.scale: 24.0
        PathAlign.forward_point_distance: 0.1
        GoalAlign.forward_point_distance: 0.1
        PathDist.scale: 32.0
        GoalDist.scale: 24.0
        RotateToGoal.scale: 32.0
        RotateToGoal.slowing_factor: 5.0
        RotateToGoal.lookahead_time: -1.0
/**:
  local_costmap:
    local_costmap:
      ros__parameters:
        global_frame: TB3_1/odom  # 전역 프레임
        robot_base_frame: TB3_2/base_link  # 로봇 기준 프레임
        update_frequency: 5.0  # 맵 업데이트 주기
        resolution: 0.05  # 맵 해상도
        width: 3  # 맵 너비 (미터 단위)
        height: 3  # 맵 높이 (미터 단위)
        obstacle_range: 2.5  # 장애물 감지 범위
        raytrace_range: 3.0  # 레이 트레이스 범위
        rolling_window: true
        plugins: ["obstacle_layer", "inflation_layer"]
        obstacle_layer:
          plugin: "nav2_costmap_2d::ObstacleLayer"
          enabled: true
          observation_sources: scan
          scan:
            topic: /TB3_2/scan
            max_obstacle_height: 2.0
            clearing: true
            marking: true
            data_type: "LaserScan"
        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
          inflation_radius: 1.0
          cost_scaling_factor: 3.0
